### ISSUE TITLE
Add compatibility with cats.InjectK once cats 1.0.0 drops

### ISSUE THREAD

**Issue by andyscott** [frees-io/iota#21]
https://github.com/typelevel/cats/pull/1642 will allow direct compatibility with `InjectK`.

**Comment by diesalbla** [comment]
@andyscott The PR in `cats` was merged. ¿Should we proceed with this issue?

**Comment by andyscott** [comment]
We can get a PR up but we won't be able to merge until we switch to cats 1.0

**Comment by andyscott** [comment]
Addressed in #58
