### ISSUE TITLE
Ensure `.asType.toType` is called in a safe manner

### ISSUE THREAD

**Issue by andyscott** [frees-io/iota#26]
See https://github.com/47deg/iota/pull/24

I think we are safe already as we are calling `.asType.toType` on the symbol from `TypeRef`s _after_ typechecking. But I'm not sure, so I have followed up by asking on the scala/contributors gitter. "Worst" case I will add guard statements to the existing code and have helpers return `NoType` when the conversion can't be performed.

**Comment by alexflav23** [comment]
This is used in reflection API right? Because I was testing in macro API.

**Comment by andyscott** [comment]
It's used in both! There are direct tests for the reflective helpers, and those same methods are used "transitively" by the macro methods, which are also tested.
