### ISSUE TITLE
Ensure correct attribution is made for Matryoshka based code

### ISSUE THREAD

**Issue by andyscott** [frees-io/iota#37]
The following file is derived from Matryoshka: https://github.com/47deg/iota/blob/6f245e5df0927f7e541fb0be5e545253a05bee05/modules/core/src/main/scala/iota/internal/catryoshka.scala

Attribution is made and the original source is under the same license as Iota. However, I'm not sure if it's done correctly as Matryoshka's licensing/copying information is a bit spread out.

**Comment by andyscott** [comment]
@sellout any chance you could take a peek and let me know if we need to change anything?

**Comment by sellout** [comment]
I think that looks fine. Thanks.

**Comment by andyscott** [comment]
👍 thanks! We can also add a link to Matryoshka in the main README, if you'd like. Even once/if Matryoshka is ported over to Cats, we will probably maintain our own mini version here for the sake of keeping dependencies minimal.
