### ISSUE TITLE
Dependency on both lightbend and typelevel versions of scala-library

### ISSUE THREAD

**Issue by jrgonzalezg** [frees-io/iota#44]
I am trying to bundle an app that depends on freestyle as a single jar using sbt-assembly and i am getting conflicts about duplicate classes from scala-library. The issue seems to come from iota which shows this dependency tree including both versions of the scala-library (the tree is generated using https://github.com/jrudolph/sbt-dependency-graph):
```
[info] io.frees:freestyle_2.12:0.2.1-SNAPSHOT [S]
[info]   +-com.47deg:iota-core_2.12:0.2.0
[info]   | +-org.typelevel:cats-core_2.12:0.9.0
[info]   | | +-com.github.mpilquist:simulacrum_2.12:0.10.0
[info]   | | | +-org.scala-lang:scala-library:2.12.2
[info]   | | | +-org.typelevel:macro-compat_2.12:1.1.1
[info]   | | |   +-org.scala-lang:scala-library:2.12.2
...
[info]   | +-org.typelevel:scala-library:2.12.1
...
```

I have searched this repo and the only reference to typelevel seems to be in the scalaOrganization at file https://github.com/47deg/iota/blob/master/project/ProjectPlugin.scala which may also explain why i am getting org.scala-lang:scala-library in version 2.12.2 and org.typelevel:scala-library in version 2.12.1. It seems that the scalaOrganization defined as typelevel or some other sbt configuration may be causing the problem. Ideally since most projects will already include org.scala-lang:scala-library anyway it may be better if no dependency on the typelevel version existed although i am not sure about the implications of this.

**Comment by andyscott** [comment]
Typelevel Scala is used for singleton literal support for some of the type list operators (an undocumented feature, for the time being). TL Scala is only needed for the tests to compile so I will see what I can do to fix this issue.

**Comment by andyscott** [comment]
I've finally dug into this issue and I should have a solution soon.

**Comment by anatoliykmetyuk** [comment]
Any updates on this bug? Can we hope it to get fixed in the near future?

**Comment by andyscott** [comment]
I couldn't sort out how to make this work with TLS, so I have a local build with an easier solution: split the tests into a separate module. Use LBS for core, and TLS for tests. The only issue holding me back is the cross build setup to make sure Scala libs are assigned correctly across 2.11 vs 2.12.

I will revisit this and try to have a fix out within a week.

**Comment by andyscott** [comment]
I finally got a fix together. Awaiting review and merge of #63.

**Comment by anatoliykmetyuk** [comment]
Awesome news, finally it will be possible to ship freestyle-based apps with the assembly plugin. Thanks for your work @andyscott!

**Comment by andyscott** [comment]
Sure thing. It wound up being substantially more complicated originally anticipated due to a slew of SBT plugins and the need for cross building across different Scala versions.
