### ISSUE TITLE
Consider refactoring/renaming items for consistency

### ISSUE THREAD

**Issue by andyscott** [frees-io/iota#51]
With the potential inclusion of `QList` and `CopQ`, we will have:

`Cop`
`CopK`
`CopQ`
`TList`
`KList`
`QList`

What about refactoring this into to:
 
`Cop`
`CopK`
`CopQ`
`TList`
`TListK`
`TListQ`

This simplifies names, IMHO, because the suffix always indicate the kindness. This is in alignment with other libs like cats.

/cc @raulraja @peterneyens @juanpedromoreno @diesalbla

**Comment by peterneyens** [comment]
Makes sense.

The suffixes beyond `TList` and `TListK` are not as easy though.

I see educational purposes for coproducts for `F[_[_], _]` and `F[_, _[_], _[_], _]` (which I dubbed `Q`).
I have seen the first described as `KA` (if we follow the same convention, `Q` would be `AKKA` :smile:).
