### ISSUE TITLE
Add type safe value accessor methods to product types

### ISSUE THREAD

**Issue by fommil** [frees-io/iota#83]
It would be good to have an accessor for products and coproducts.

Even better if there was a way to get a tuple / nested scalaz disjunction.

And for products, even better if there was a macro that allowed me to pass a `Prod` to a method that accepts X parameters :smile:

**Comment by andyscott** [comment]
- For accessors to products, do you mean type safe indexed based accessors?

- It would be reasonable to provide two/from tuple conversions for `Prod` for valid tuple arities.

- What would that look like?


For the last point, consider:
```
def methodTakesManyParams(a: String, b: Double, c: Int): Foo = // ...
val prod = Prod[String :: Double :: Int :: TNil]("hi", 1.0, 100)
```
I don't think there's a way to support syntax such as
```
methodTakesManyParams(prod.expand)
```
The following may be possible, though:
```
prod.passTo(methodTakesManyParams)
```

**Comment by fommil** [comment]
`prod.passTo` sounds good! I don't really care about typesafe indexing (although that would be pretty cool if the index was passed as a constant!)... a `.toTuple` or something would be nice as a basic way to access, but maybe best not to add features that aren't needed.

**Comment by andyscott** [comment]
I broke this out into #98 and #98 for the second and third bullet points.
