### ISSUE TITLE
Add ability to zip products (and maybe coproducts?)

### ISSUE THREAD

**Issue by fommil** [frees-io/iota#85]
it would be good to be able to zip together products, getting back a product of tuples

and it would be good to be able to zip a product with a coproduct, getting back a coproduct.

and zipping coproducts ... but I'm not sure what that would give back. possibly a `Maybe` of tuple?

**Comment by andyscott** [comment]
I think zipping two products of the same types would be a reasonable addition to Iota. For the other operations, I would be happy if the building blocks were present so that they could be built ad-hoc without any casting.

**Comment by fommil** [comment]
cool, if you can show me an example of zipping a product with a coproduct and a coproduct with a coproduct, I can go the adhoc route.

**Comment by andyscott** [comment]
Sure thing! It will be easy once I add a "zip" like operator.
